### ISSUE TITLE
"ScreenVoice/SeikaCenterAPI.dll" can't be redistributed. 

### ISSUE THREAD

**Issue by k896951** [ikihiki/ScreenVoice#1]
Hi.
I'm a developer and publisher of SeikaCenter.

If "ScreenVoice/SeikaCenterAPI.dll" was downloaded from hgotoh.jp, please do not include "SeikaCenterAPI.dll" in ScreenVoice.
I don't allow others to redistribute "SeikaCenterAPI.dll".

**Comment by k896951** [comment]
リポジトリからSeikaCenterAPI.dllを削除していただけますようお願い申し上げます。

あなたがリポジトリに公開しているSeikaCenterAPI.dllは ハッシュ値やプロパティの情報から 当方のサイト hgotoh.jp よりダウンロードされたものだと思われます。
このDLLはあなたのプロダクトに同梱して配布することを許していませんし、事前にあなたからご相談のメール等を頂いたこともありません。
また、あなたのコードを見た限りDLLがなくても動作するかと思います。
DLLをリポジトリから削除していただけますよう、お願い申し上げます。

**Comment by ikihiki** [comment]
削除しました。
